image: node:10

stages:
  - build
  - test
  - deploy

cache:
  paths: 
    - node_modules/

before_script:
  - yarn install --frozen-lockfile

build:
  stage: build
  script:
    # When the CI flag is set to `true` (which it is by default), warnings are treated as errors.
    # Unfortunately, some of the rdflib dependencies depend on outdated libraries, which are spewing
    # some Webpack errors. I don't want to eject to fix those warnings, or track down all relevant
    # dependencies to submit pull requests to update _their_ dependencies, so since the warnings
    # pertain to code we're not running anyway, let's ignore them for now (`CI=`):
    - CI= yarn run build
  artifacts:
    expire_in: 1 month
    untracked: true

test:
  stage: test
  script:
    - yarn test --ci
  artifacts:
    expire_in: 1 week
    paths:
      - coverage

pages:
  stage: deploy
  script:
    # The `public` folder contains public assets for CRA,
    # but GitLab Pages wants it to contain the built app
    - rm -r public
    - mv build public
    # Make sure all routes load the app, which can then do client-side routing:
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public 
  only:
    - master # this job will affect only the 'master' branch
